### ISSUE TITLE
Preserve scrolling position when clicking back the first time

### ISSUE THREAD

**Issue by matthew-g-morrison** [DockYard/ember-router-scroll#173]
I believe version 1.0.1 introduces some unexpected behavior. The first time a user click the browser's back button, the scroll position is not preserved.

I have a long list of link-to components, and am doing the following:
1) refresh the page with the link-to list
2) find a link-to near the bottom of the page and click it 
3) click the back button

The page automatically scrolls to the top of the page.

4) scroll to a different link-to near the bottom of the list and click that
5) click the back button

Now the page does not automatically scroll to the top of the list, but instead preserves the original scroll position.

**Comment by lougreenwood** [comment]
I've also encountered this in a 2.18 application. downgrading to 1.0.0 works

**Comment by snewcomer** [comment]
I'm unable to reproduce in the dummy app.  I'm wondering if this relates to `delayScrollTop` as a config env.  Does your app optimistically render or pause at the model hook?
