### ISSUE TITLE
Setting locationType and historySupportMiddleware still needed?

### ISSUE THREAD

**Issue by GCheung55** [DockYard/ember-router-scroll#174]
According to #54, it seems like step 3 in the docs, to update `locationType` and add `historySupportMiddleware` isn't needed. Is that correct?

If not, can we update the docs...?

**Comment by CvX** [comment]
The `historySupportMiddleware` option is still useful/required, but the `locationType` wasn't necessary for quite some time. I've opened #205 to update the README.
