### ISSUE TITLE
HistoryLocation Subclass Question

### ISSUE THREAD

**Issue by stefanpenner** [DockYard/ember-router-scroll#193]
I was reading the code for `addon/locations/router-scroll.js` and I'm not totally sure if it is required any longer.

The two methods it overwrites are `pushState` and `popState`, but when reading ember's latest history_location implementation, it appears to essentially do the same. The exception being, the subclasses methods, do not set `this._historyState`. 

If the reason for the subclass is to avoid setting `_historyState` then, i suppose it needs to remain. (Although a comment as to why, would be great). But if we don't need to avoid setting `_historyState` then we should likely just use the default history location object.

**Comment by snewcomer** [comment]
Agreed.  Can't believe this hasn't been removed!  Plan for removal in 2.0

https://github.com/dollarshaveclub/ember-router-scroll/pull/201
