### ISSUE TITLE
Release new version with fixed Ember 3.9 deprecations

### ISSUE THREAD

**Issue by tansongyang** [DockYard/ember-router-scroll#200]
It looks like https://github.com/dollarshaveclub/ember-router-scroll/pull/191 fixes Ember 3.9 deprecations and was merged quite a while ago. When can we expect a new release? We're upgrading and trying to get rid of all our deprecation warnings.

**Comment by st-h** [comment]
same here. Looks like there currently is an issue with publish rights: https://github.com/dollarshaveclub/ember-router-scroll/pull/198#issuecomment-494006241

**Comment by snewcomer** [comment]
DSC has been nice enough to transfer this repo.  Awaiting the final transfer hopefully in the near future.

**Comment by duggiefresh** [comment]
@dollarshaveclub  👋Howdy y'all. Would it be possible to grant DockYard the npm rights to publish a new release. Thank you!

**Comment by knownasilya** [comment]
Would love to get a release with the new service feature. Thanks for the hard work!

**Comment by snewcomer** [comment]
Me too :) Hopefully can get the npm org transfer done soonish.  Awaiting.... .... ....

**Comment by Turbo87** [comment]
@snewcomer it looks like the npm user `dockyard` has access to the package now, so I guess the transfer is complete? :)

**Comment by snewcomer** [comment]
Sweet! 1.2.0 published!  Thanks everybody.
