### ISSUE TITLE
preserveScrollPosition doesn't work

### ISSUE THREAD

**Issue by sergchernata** [DockYard/ember-router-scroll#224]
I tried to implement `preserveScrollPosition: true` for a specific controller in all 3 documented ways. None of them seemed to have any impact.

I have a `select` element that updates the corresponding query param on change and it makes the page scroll jump to top every time.

```
"ember-cli": "^3.10.1",
"ember-router-scroll": "^1.1.0",
```

**Comment by snewcomer** [comment]
@sergchernata Do you have a minimal repo?  I'll try and check this out by Friday...

**Comment by snewcomer** [comment]
I can't reproduce, but doesn't mean your example can't!  Also you can try updating to latest - 1.3.2

**Comment by st-h** [comment]
@sergchernata I was just debugging an issue with scrolling myself, and noticed that one of the things that easily could go wrong is having the wrong scroll container configured. I do not use the window as scroll element, which requires additional config: https://github.com/DockYard/ember-router-scroll#target-elements
Configuring the Addon correctly fixed all my issues so far. Might be that you are having a similar issue. Hope this helps.

**Comment by snewcomer** [comment]
Closing for now!  Let us know if you have these same issues!
