### ISSUE TITLE
Provide non Mixin approach

### ISSUE THREAD

**Issue by mehulkar** [DockYard/ember-router-scroll#233]
In Ember Octane, the `Router` class is generated as a native class. 

Because it's still based on an Ember core object, mixing in RouterScroll still works:

```js
import EmberRouter from '@ember/routing/router';

export default class Router extends EmberRouter.extend(RouterScroll) {
}
```

but in the long term, it would be good to remove the dependence on the Ember object model and provide a different way to provide this feature.

**Comment by snewcomer** [comment]
100% agreed!  I can look into this by the end of the week.  Thanks for filing!
