### ISSUE TITLE
Could not find module `ember-test-waiters` imported from `ember-app-scheduler/scheduler`

### ISSUE THREAD

**Issue by AleksandrBorovkov** [DockYard/ember-router-scroll#251]
I've got error after installation

![image](https://user-images.githubusercontent.com/22237897/81961750-79cd4300-961b-11ea-9828-7be4b19e95a5.png)

**Comment by snewcomer** [comment]
Seems like you might have a dependency that is super-ceding the one installed here.  Specifically ember-app-scheduler.  Might checking out dependency-lint or your package.json to see if this is the case?

https://github.com/salsify/ember-cli-dependency-lint

**Comment by AleksandrBorovkov** [comment]
Here is result of dependency-lint

![image](https://user-images.githubusercontent.com/22237897/82152894-01f65700-986d-11ea-898b-6c2cce921b1c.png)

**Comment by snewcomer** [comment]
Is this still a problem for you?  Closing for now but please open up agin if you need to!  `v3.3.3`
