### ISSUE TITLE
Deprecation warning still present in 4.0

### ISSUE THREAD

**Issue by gzurbach** [DockYard/ember-router-scroll#271]
Hi there! 

I just updated `ember-router-scroll` to `^4.0.0` in my app (Ember 3.16) and I am seeing the following warning in the console:

`DEPRECATION: The use of Ember.Router in setupRouter is deprecated. Please use the router service.`

I thought that v4.0 was supposed to address this? Am I missing something? 

Thanks a lot for all the good work! 👍

**Comment by snewcomer** [comment]
Huh interesting!  Do you call `setupRouter` in your app code.  I believe we are doing the right thing on our side.

https://github.com/DockYard/ember-router-scroll/blob/b63ef851801b41d60fe776c7e214e25efaf213d3/addon/services/router-scroll.js#L84

**Comment by gzurbach** [comment]
There is no trace of `setupRouter` in my app code. Also, uninstalling `ember-router-scroll` does fix the warning. But then I don't get that sweet sweet scroll to top behavior 😅 

It does appear that this plugin is doing the right thing, which is why I am confused as well. It would be interesting to see if others experience the same issue.

**Comment by gzurbach** [comment]
I think I figured it out. The deprecation warning seems to be erroneous in `ember-app-scheduler`:

https://github.com/ember-app-scheduler/ember-app-scheduler/blob/master/addon/scheduler.ts#L84

The second parameter is documented as follow:
> If **falsy**, the deprecation will be displayed.

Therefore, `router instanceof Router` should be `!(router instanceof Router)` or `router instanceof RouterService`.

**Comment by rwwagner90** [comment]
Seeing this issue as well.

**Comment by gzurbach** [comment]
This issue was fixed in `ember-app-scheduler@5.1.2` released a few hours ago. Uninstalling and reinstalling `ember-router-scroll` allowed npm to pickup the new version. Problem solved!

See https://github.com/ember-app-scheduler/ember-app-scheduler/pull/962
