### ISSUE TITLE
Upgrade to version 4.x leads to test errors

### ISSUE THREAD

**Issue by freyjameetsmel** [DockYard/ember-router-scroll#273]
I'm trying to upgrade `ember-router-scroll` from v3.3.3 to v4.x in our project. I did the necessary adjustments in the `router.js` according to the README. The project starts and works as expected. 

Some tests however do not run smoothly and thow the following error message:

> Assertion Failed: You attempted to remove a function listener which did not exist on the instance, which means you may have attempted to remove it before it was added.

Not sure what causes the issue but it only seems to occur after the version upgrade and following necessary code changes.

**Comment by snewcomer** [comment]
👋  Thanks for the issue! I just upgraded ours and did not see this. I'm guessing it is this line.  Do you do any funky stuff in a test like patch/override properties on the service?

https://github.com/DockYard/ember-router-scroll/blob/master/addon/services/router-scroll.js#L93

**Comment by cah-briangantzler** [comment]
We updated to version 4 and did not get failing tests either, however when I upgraded to ember-qunit 5 I now get the failing tests with the above message. So Im guessing thats the difference.

**Comment by freyjameetsmel** [comment]
> We updated to version 4 and did not get failing tests either, however when I upgraded to ember-qunit 5 I now get the failing tests with the above message. So Im guessing thats the difference.

This is something I need to check tomorrow. I think we did upgrade to ember-unit 5 as well in the last weeks.

**Comment by bobisjan** [comment]
We have this error after upgrade to the new `ember-qunit#5` and `@ember/test-helpers#2+` too.

By quick debug I've noticed that [destroy()](https://github.com/DockYard/ember-router-scroll/blob/master/addon/services/router-scroll.js#L94-L109) method is called twice during test teardown.

Switching to `willDestroy()` method seems to be working, but I'm not sure if it is intended/proper fix.

**Comment by SergeAstapov** [comment]
Potentially fixable via #280

**Comment by jherdman** [comment]
I can confirm #280 resolves this issue. Any chance we could get some eye balls on that PR @snewcomer ? <3

**Comment by snewcomer** [comment]
4.0.3!
