### ISSUE TITLE
README Correction - export DEFAULT class...

### ISSUE THREAD

**Issue by nadnoslen** [DockYard/ember-router-scroll#278]
The README's `> 4.x` section has a type; should read `export default class ...` ... the `default` is missing.

This can lead to strange message about not being able to find `router:main` at runtime.

This is the section of the README that needs correction:

> Usage > 4.x
> ------------------------------------------------------------------------------
>
> Users do not need to import and extend from `ember-router-scroll` anymore.  In order to upgrade, you should remove this > import.
>
> This is what your `router.js` should look like.
>
> ```js
> import EmberRouter from '@ember/routing/router';
>
> export class Router extends EmberRouter {
>  ...
> }
>```

**Comment by nadnoslen** [comment]
See #279 for fix

**Comment by snewcomer** [comment]
Thank you!!
